sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: kuZUGFbO1yNhfziLKY8gJ8++DEVsk2bTuBNzjNsI+Vpc4uyBiGtm+41ldLg74aR/KO840PHfWJkR/194QpJWH9sopd1up6ItfUJlcHhmq0jA5TJqX8dYkRrT+qyn2mpy1GwGX1lOR01pXe8I4u1efXWq/qiPEc6Kyek0HRmK6kFCnOI5peOjoSJvGdlKUjgOFh/xRAk26O3/bA/ORJ7sBpYbLvlhtOdmx/TmRmTaMmEsEL5L8W9D86rIk1rSAZ4GweuCbXStLCLcWLnMlWEmIxyygccNUUZrNei65lip4JRwkBZWkI3NIQCN/bWk1C4WyWsv6zfgjYwcK6ti5ZBK7XBzWlJQc0p8gAxN/EY8ZxMhlRhXF6xOaV3CgauWUVxYFwfr39kfuIn8gU0QyDPWp9LQ9aTRwr7ZNgN6H0/qgaMt6P7ffGfBRJq5Vo1D0jKyOUi6/LbtN3l/RsTGw6RlnfnXOPcxWq4pnxkI5yueBuH+DZseLbprkgj8/zgDRy8AIePfyKL/S+xFezv29QktrzMGk+4gT2h72f1Y9VVg80+TSG6xg7IVtSHR+Ht4lwDmMzANyGQM/Th2X2CclN2F3Rd7tWYUOq7BG2PPRGjypV5jg9ggWq07V4islX52fYxwLqfcU04bByZFsvM+unbxXLvPkehg5iQYTsf+Z+n9+EA=
  - secure: EqtVKCK+VEigckkPWRW6LsxwqDgFsGKLeHV4uGYoabHWueJSqfLY8jFZoo5fC0Napd3QSZwEw7AvQhicrVTYIbY7l6aZ1PM9HqLL6xNZenkkAoLg2oqibmU7qwhPs915V3HNS2MiDJsX+rSoqpi7b4MPjDmZLJ9ODp90QBgF96288cNXREZvn5nJXzrbbJNfoqQZamK/qBzUrDJ89FjbIe+ZKcJS41uC9JcmpyHWwQIi7NTiBmPsDsdiNYa8AcPTDcRUZ1MiT85HGHtIEuVfOvjbrNTzPNVQok1SAZOBMu6WQUYUnN1F7etTHVqiI2a/VDlQoYDki9RMhKLiutsRDPrKhpxgKS/D4LETHcREJNFSNeHzi8s98p4AqcH/RTYQaPChbd0Zf5ipYJBd+BJibD1O6SPYAMQm5+MgQ4XtWy1LoonmPDbVFPUK2nOpQ0w61N46ODbTT6d1ZYX83LKccL+y3FUTzK8RZ6VpmEHHP4N50lDiq9AmmCAlJ8Q3n/7IFyFJ/3r/DXYZ5GAc/mtjcUa9h3tPQPptug95XH0iBEUbPNo3AlLS1YNQyZ7VjRIlTNPMzfjxTgx9OkKsy9NIXNpDMJquHwM8tglUiTGHgSTR1t5kOOxf0AYo22YMXV15mmpiiBEVyg9ZO7RRo5Lvb4NchXSHjmGrizQgcgJELaI=
  - secure: MAhHHN11ylWetcHtc6103RL26XTVSxE44WKTIeDUuPIOzqy5xCQAVyQWsDTVHJI8Db2hQW54kWI9UQ8RSuSI0pH51VtaCkn3jG5ab+peNhi8Vv/cNALBHU5+wRW4fg/sVrK1XcDMtaw0HBAGur6wFVckkNi1loAsBz0SWmeE6pudKm8P98Og0/9wpfFGTvNSTkZp4waMd+ViqWXfqcDbnuEKv6haUh3jOjqSekXQIDqgCEMn/qaq2srLkrTY0d0iOI7evjl8XHnz3W9GOOVCGKlEcL8RCDqZvDi+TxUJXQj9+oq/xc1CxZaBqRwNkYZSYRsxad4iduEbebfxvXSjGpuXaHx/Pcj5JZrLOIr7uJm2YcC/7IzpxoFB8lrW6W4iGE4b7h6e/PB4QQWaODoohJbK77aj+C6ouFprWiOfC6vsgUR6AJzSzHMnldtIsAAtMYniqIfBNlOCCylwyqjtTS4pZJYC4CXDIUqet1aWyB1763kCL59K9RevLSvLyekmjVx/hz0ls08sf8QqJz3mOWsgX3WCe1HkQo7oBfW51IVBF3rAyrQlnHZSWwJ41szbicpqMz9DbabpPXi9XLJGkXpKbHCUaG7tDcbSFkl0ymMauKqR3+ulXjYj8fvhLRJLcyEu8WZqzUv+Hrej69bT6CTLnuTD5I5azQhjRMMRcCw=
  - secure: V76y0w6Xm2QA95cU7AAGjmYgT6SCgVEtJmRwM1DvLfcyy4EiBE5X6qYS3a//bBJ4YkEpX/yjaStnkAI7S2cdb+p3N62ui+rJYmmPgP4OW2S+W3cerU21/Hp7ZSYXHulgK6qioQ5dPJ5gSqWyaKiMhXmuYuNw8wLAFQvbMD6BKJCuuAyqmn1xd1ribEc5c2YdsVevLB4JNlz+WprCsvmmmx/HHVrXMNv8zcEiuh6u13m49VibHVzn/MW7D8ty++2nfJurm/zxyVCJvZQ9xu39Ndynf9caML+IhSq+PBgyrEIOFqETXEKS1nCYC0m9HdAEAZplD7Kq6IU9JFg4c9lZhWUuj1UyrjrGcPK2whiBU9WIVZN7SJ/HKz/kJiXn3Lt2jsqwEsYZZdVi5ITZcMTusn7x0N/KdXV1MkXSecedQtR8OfkX63/JZP3k5fsTuZnziEkICuYVfg7SefTeOR/0+nRqbjRtPcVYPVbuoQ826vHhKedgbooH+z9jS/WhVNtfOEe9/7vB6kzkaYZuoeYw99rjqLNBD5oRroyVWjR3lQ6AG2ICgFvc20VkizYPSdx3o77DOS5W/LAmdvhE/+4drWCF1MxdDsUimF1n8+Vn6Ifxu0/Vre9kLP8Fq55VXbVO/a4u+1J1yakXbgKmNygvKNbnKErdlZso8Oaw18x4d+Y=
