sudo: false
dist: trusty
language: node_js
node_js:
- lts/*
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
env:
  global:
  - secure: gc+6BTyaQREea3sYlG3FrsNdEyRSWR4jo5UHMszsIEnvrlfZil67pGr8Bco5Gvy/1UKXP45Gl0fwv3LhyN+0lgQ+qJNBlWKVw8j5jMDGHwQIu/j3/+Wd2v3I9jUbzZaHzijmtcemQ7ZIms96tYHZkjlqDYkF537aVnp3OMvkYVg/cRtKK0RLwE8oUpL6Tgstko+dEvAuhIAw2BOX3OfT1bGNvY2fV7ELGZ+WcDL2V/V7zm4aRJ1FoDG8geZNaGLgJNT8BVv/nmco9J9aGbnutvgW3lTEZK+hgVKNxcYhRauk8Vfsztwrvu9MFgmLPUCBcyU3lDtiKRj0kEFb3JqV5mZlejmZ8MsyQkHp8TTkFyJQ+kdAD5nze56+hGCe+F39t0JDoxvcmRCaZE3/hKoExKUq2i56pZ9+nOQtt4sR/8VDxpHWusY68NiIF0N7T3iP0SQ5MYA3JkCglRgFnyX2ssjlLz0H8XHN10J8utwlIiF/5A6sIg/uFRZ9FCby9o0nEwrMz0OgH1XG3vSS3MKrXMOqrYuKZXtYYtXVeYFqUhPgUIfewc8VO3tDKDTdM/k2vXIIBWXD7cNlKH+pZdA26p3Lbt9XXCAcGeMsy+uuZxwd8T15LsrE1gI81FcGf/3TmpAw7vQTPRZPILfVFGHvSxvmoh3UfrwmhFpxQaPSokc=
  - secure: XFT4A1IDAO39C8HwqrjWEkd7od1Smt5ZIJ7nrmT+QbmSqFqtUiSisVULjD57luPFWZIPBUwj5TtxupdpMRFm5BdtVrzNS3KY3EzEhpY3r2pvDU522UFKJ1oEY296mt6FFbz8Nm0lP0rDjhq4CXZ3DkR1c/xjEWWH/4X8dBd3fe8noKqahcehIDhb3YpRz8Noz9JyyM0UgRSOVtxV5/PIia80snkeH1cjyFv1BNg1ovyAxAX4ZKJPmjAvekqYmKTuDWcuLai9E8ZOMSCraZq6SzSouq7KZ9DCR9lefOydRTIMiQSrVWd7YZs9kkORAnCZe1LFpau42aSpP5AmK8rn69GWEzdDKtON734m1T79GGGe9fwZiApNIGdiB5qqL2T+8N53OoGxMO7YXLHkNieQw9ujYzocthUNOasNxe4QA8PphPSK2ugunWVoTMmjhSRsHIfDkHY/dERCf+iyeIhP0p9OjljeuUV9lIHbjpYuxU3XHFLLAR85v4jMOcwkw6O6GnCQM3M4LqEHQnKN1cWXRyysaiHwpR0LaCqQM/YAivyi8DCbpb9sIhf9IaQOZ6qIu5uMmlBVlnF+zIRg2eSmDyApzJocDZT3tvFHAc1xLN6yUwQh8InpHEYlazlRWJXLiqIP+YG1+1ZKurEAOheNk9/Kj1FKhwTpNXa2ShJRsJQ=
